# This workflow deploys the application to the Linode server

name: "CD Docker Deploy"

on:
  workflow_run:
    workflows: ["CI Docker Build and Publish"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env: 
      TAG: "ghcr.io/cormazz/dance-tech:latest"

    steps:
      # https://github.com/actions/checkout
      - name: Checkout repo
        uses: actions/checkout@v5

      # https://github.com/docker/login-action?tab=readme-ov-file#github-container-registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          

      # https://github.com/appleboy/ssh-action
      - name: SSH and deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # If you use `./deploy.sh prod restart` the container image doesn't update
          script: |
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ${{ env.TAG }}
            cd apps/dance-tech
            ./deploy.sh prod down
            ./deploy.sh prod up



